apiVersion: v1
kind: ConfigMap
metadata:
  name: __configname__
data:
  DATASOURCE_URL: __datasourceurl__
  DATASOURCE_USERNAME: "sercomvas"
  DATASOURCE_PASSWORD: "sercomvas"
  BIZMGR_URL: http://10.161.1.237:9323/cbs-api/3.0/businessmgr/
  ACCTMGR_URL: http://10.161.1.237:9323/cbs-api/3.0/accountmgr/
  BBMGR_URL: http://10.161.1.237:9323/3.0/bbmgr/
  BCMGR_URL: http://10.161.1.237:9323/3.0/bbmgr/
  USSD_PUSH_URL: "http://10.155.10.12:9314/sms/rest/submit/send-ussd-push"
  SEND_SMS_URL: "http://10.155.10.12:9314/sms/rest/submit/send-sms"