apiVersion: v1
kind: Service
metadata:
  name: __servicename__
spec:
  selector:
    app: __containername__
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 7887
  type: LoadBalancer